/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/EjZX9gvGYUL
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";

import Link from "next/link"
import config from './config'; 
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { DropdownMenuTrigger, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem, DropdownMenuContent, DropdownMenu } from "@/components/ui/dropdown-menu"
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import React, { useState, useEffect } from "react";

export default function Otapage1(){

        // Use separate state variables for temperature and humidity
        const [temperature, setTemperature] = useState("NULL");
        const [humidity, setHumidity] = useState("NULL");
        const [version, setVersion] = useState("NULL");
        const [status, setStatus] = useState("NULL");
        const [formattedLastSeen, setLastSeen] = useState("NULL");
        const [isGreen, setIsGreen] = useState(false);
        const baseUrl = process.env.NODE_ENV === 'production' ? config.production.baseUrl : config.development.baseUrl;
        // Function to fetch sensor data from the API
        const getSensorsData = async () => {
          try {
              // Fetch device status from the /get-device-status endpoint
              const statusResponse = await fetch(`${baseUrl}/check-device-status`);
      
              // Check if the status response is okay
              if (!statusResponse.ok) {
                  throw new Error('Network response was not ok');
              }
      
              // Parse the status data
              const statusData = await statusResponse.json();
              console.log('Device Status:', statusData);

              // Convert the last seen timestamp to a Date object
              const lastSeenDate = new Date(statusData.lastSeen);

              // Convert the date to a UNIX timestamp in milliseconds
              const lastSeenTimestamp = lastSeenDate.getTime();
              console.log('Last Seen:', statusData.lastSeen);
              console.log('Timestamp:', lastSeenTimestamp);

              // Calculate the current time in milliseconds
              const currentTimestamp = Date.now() - 10800000; 

              // Calculate the difference in time in seconds
              const timeDifferenceInSeconds = (currentTimestamp - lastSeenTimestamp) / 1000;

              let formattedLastSeen;
              // Format the time difference based on the magnitude
              if (timeDifferenceInSeconds < 60) {
                  // If the difference is less than 60 seconds
                  formattedLastSeen = `${Math.round(timeDifferenceInSeconds)} seconds ago`;
              } else if (timeDifferenceInSeconds < 3600) {
                  // If the difference is less than 60 minutes (3600 seconds)
                  const minutes = Math.floor(timeDifferenceInSeconds / 60);
                  formattedLastSeen = `${minutes} minutes ago`;
              } else if (timeDifferenceInSeconds < 86400) {
                  // If the difference is less than 24 hours (86400 seconds)
                  const hours = Math.floor(timeDifferenceInSeconds / 3600);
                  formattedLastSeen = `${hours} hours ago`;
              } else {
                  // If the difference is 24 hours or more
                  const days = Math.floor(timeDifferenceInSeconds / 86400);
                  formattedLastSeen = `${days} days ago`;
              }
              // Log the formatted last seen time
              console.log('Last Seen:', formattedLastSeen);

              // Update the state with the formatted last seen time
              setLastSeen(formattedLastSeen);
              setStatus(statusData.status);
              
              // Check if the device status is "Online"
              if (statusData.status === 'Online') {
                  setIsGreen(true);
                  // Fetch sensor data from the /get-sensor-data endpoint
                  const response = await fetch(`${baseUrl}/get-sensor-data`);
      
                  // Check if the response is okay
                  if (!response.ok) {
                      throw new Error('Network response was not ok');
                  }
      
                  // Parse the sensor data
                  const data = await response.json();
                  console.log('Sensor Data:', data);
      
                  // Update state variables with the fetched data
                  setTemperature(data.temperature);
                  setHumidity(data.humidity);
                  setVersion(data.firmwareVersion);
              } else {
                  setIsGreen(false);
                  // If the device is offline, set the state variables to default values (e.g., null or 0)
                  setTemperature('0.0');
                  setHumidity('0.0');
                  setVersion('1.0.0');
              }
          } catch (error) {
              console.error('Error fetching data:', error);
          }
      };

        const [serialMessages, setSerialMessages] = useState([]);

        // Function to fetch the latest 10 serial messages from the server
        const fetchSerialMessages = async () => {
          try {
              // Fetch the latest 10 serial messages from the server
              const response = await fetch(`${baseUrl}/latest-serial-messages`); // Adjust the URL as needed
              if (!response.ok) {
                  throw new Error('Failed to fetch serial messages');
              }
              const data = await response.json();

              // Combine the messages from the data array into a single string
              const messages = data
                  .map((msg) => `> ${msg.message}`) // Add '>' prefix and separate lines
                  .join('\n'); // Join the messages with a newline character

              // Update the state with the combined string
              setSerialMessages(messages);
          } catch (error) {
              console.error('Error fetching serial messages:', error);
          }
      };
    
          // Run the fetch functions when the component mounts
          useEffect(() => {
            // Call the functions once when the component mounts
            getSensorsData();
            fetchSerialMessages();

            // Set up intervals to call the functions every 5 seconds
            const sensorsDataInterval = setInterval(getSensorsData, 5000);
            const serialMessagesInterval = setInterval(fetchSerialMessages, 5000);

            // Cleanup the intervals when the component unmounts
            return () => {
                clearInterval(sensorsDataInterval);
                clearInterval(serialMessagesInterval);
            };
        }, []);

  return (
    <>
    {/* PAGE 1*/}
      <div className="grid min-h-screen w-full lg:grid-cols-[280px_1fr]">
        <div className="hidden border-r bg-gray-100/40 lg:block dark:bg-gray-800/40">
          <div className="flex h-full max-h-screen flex-col gap-2">
            <div className="flex h-[60px] items-center border-b px-6">
              <Link className="flex items-center gap-2 font-semibold" href="#">
                <Package2Icon className="h-6 w-6" />
                <span className="">IoT Platform</span>
              </Link>
              <Button className="ml-auto h-8 w-8" size="icon" variant="outline">
                <BellIcon className="h-4 w-4" />
                <span className="sr-only">Toggle notifications</span>
              </Button>
            </div>
            <div className="flex-1 overflow-auto py-2">
              <nav className="grid items-start px-4 text-sm font-medium">
                <Link
                  className="flex items-center gap-3 rounded-lg bg-gray-100 px-3 py-2 text-gray-900  transition-all hover:text-gray-900 dark:bg-gray-800 dark:text-gray-50 dark:hover:text-gray-50"
                  href="#"
                >
                  <PackageIcon className="h-4 w-4" />
                  Device Management
                </Link>
                <Link
                  className="flex items-center gap-3 rounded-lg px-3 py-2 text-gray-500 transition-all hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                  href="#"
                >
                  <LaptopIcon className="h-4 w-4" />
                  Firmware Update
                </Link>
              </nav>
            </div>
          </div>
        </div>
        <div className="flex flex-col">
          <header className="flex h-14 lg:h-[60px] items-center gap-4 border-b bg-gray-100/40 px-6 dark:bg-gray-800/40">
            <Link className="lg:hidden" href="#">
              <Package2Icon className="h-6 w-6" />
              <span className="sr-only">Home</span>
            </Link>
            <div className="w-full flex-1">
              <form>
                <div className="relative">
                  <SearchIcon className="absolute left-2.5 top-2.5 h-4 w-4 text-gray-500 dark:text-gray-400" />
                  <Input
                    className="w-full bg-white shadow-none appearance-none pl-8 md:w-2/3 lg:w-1/3 dark:bg-gray-950"
                    placeholder="Search devices..."
                    type="search"
                  />
                </div>
              </form>
            </div>
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button
                  className="rounded-full border border-gray-200 w-8 h-8 dark:border-gray-800 dark:border-gray-800"
                  size="icon"
                  variant="ghost"
                >
                  <img
                    alt="Avatar"
                    className="rounded-full"
                    height="32"
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "32/32",
                      objectFit: "cover",
                    }}
                    width="32"
                  />
                  <span className="sr-only">Toggle user menu</span>
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end">
                <DropdownMenuLabel>My Account</DropdownMenuLabel>
                <DropdownMenuSeparator />
                <DropdownMenuItem>Settings</DropdownMenuItem>
                <DropdownMenuItem>Support</DropdownMenuItem>
                <DropdownMenuSeparator />
                <DropdownMenuItem>Logout</DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </header>
          <main className="flex flex-1 flex-col gap-4 p-4 md:gap-8 md:p-6">
            <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
              <Card>
                <CardHeader>
                  <CardTitle>Device Status</CardTitle>
                </CardHeader>
                <CardContent className="grid gap-4">
                  <div className="flex items-center gap-2">
                  <ColoredCircle isGreen={isGreen} />
                    <span>{status}</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <ClockIcon className="h-4 w-4 text-gray-500 dark:text-gray-400" />
                    <span>Last seen: {formattedLastSeen}</span>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>System Monitoring</CardTitle>
                </CardHeader>
                <CardContent className="grid gap-4">
                  <div className="flex items-center gap-2">
                    <ThermometerIcon className="h-4 w-4 text-gray-500 dark:text-gray-400" />
                    <span>Humidity: {humidity}%</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <ThermometerIcon className="h-4 w-4 text-gray-500 dark:text-gray-400" />
                    <span>Temperature: {temperature}°C</span>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Firmware Information</CardTitle>
                </CardHeader>
                <CardContent className="grid gap-4">
                  <div className="flex items-center gap-2">
                    <LaptopIcon className="h-4 w-4 text-gray-500 dark:text-gray-400" />
                    <span>Version: {version}</span>
                  </div>
                </CardContent>
              </Card>
            </div>
            <Card>
              <CardHeader>
                <CardTitle>System Controls</CardTitle>
              </CardHeader>
              <CardContent className="grid gap-4">
                <Button size="sm" variant="outline">
                  <RefreshCwIcon className="h-4 w-4 mr-2" />
                  Reset System
                </Button>
              </CardContent>
            </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Serial Monitoring</CardTitle>
                </CardHeader>
                <CardContent className="grid gap-4">
                  <div className="bg-gray-100 rounded-lg p-4 dark:bg-gray-800" style={{ height: '150px', overflowY: 'auto' }}>
                    <pre className="font-mono text-sm text-gray-500 dark:text-gray-400">
                      {serialMessages}
                    </pre>
                  </div>
                </CardContent>
              </Card>
          </main>
        </div>
      </div>
      {/* page 2*/}
    </>
  )
}


function BellIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9" />
      <path d="M10.3 21a1.94 1.94 0 0 0 3.4 0" />
    </svg>
  )
}


function ClockIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <polyline points="12 6 12 12 16 14" />
    </svg>
  )
}


function LaptopIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 16V7a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v9m16 0H4m16 0 1.28 2.55a1 1 0 0 1-.9 1.45H3.62a1 1 0 0 1-.9-1.45L4 16" />
    </svg>
  )
}


function Package2Icon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 9h18v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9Z" />
      <path d="m3 9 2.45-4.9A2 2 0 0 1 7.24 3h9.52a2 2 0 0 1 1.8 1.1L21 9" />
      <path d="M12 3v6" />
    </svg>
  )
}

const ColoredCircle = ({ isGreen }: { isGreen: boolean }) => {
  return (
      <div className={`flex h-2 w-2 shrink-0 rounded-full ${isGreen ? 'bg-green-500' : 'bg-red-500'}`}>
      </div>
  );
};


function PackageIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m7.5 4.27 9 5.15" />
      <path d="M21 8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z" />
      <path d="m3.3 7 8.7 5 8.7-5" />
      <path d="M12 22V12" />
    </svg>
  )
}


function RefreshCwIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8" />
      <path d="M21 3v5h-5" />
      <path d="M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16" />
      <path d="M8 16H3v5" />
    </svg>
  )
}


function SearchIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function ThermometerIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M14 4v10.54a4 4 0 1 1-4 0V4a2 2 0 0 1 4 0Z" />
    </svg>
  )
}
